### ISSUE TITLE
Windows Github Release contains Debug version

### ISSUE THREAD

**Issue by KerstinKeller** [ArthurSonzogni/git-tui#10]
... which cannot be run on a System without VS installation

See dependency info for downloaded `git-tui.exe`
![image](https://user-images.githubusercontent.com/13848742/187424226-25abf79c-1fc2-48c3-9e6b-c0582ddaad1f.png)

I guess the problem is here

https://github.com/ArthurSonzogni/git-tui/blob/977fd4c95b029373cb47b061dced4a416c10309f/.github/workflows/build.yaml#L104-L105

Multi-configuration generators (like Visual Studio, which I guess would be the default for Windows), don't really recognize the `-DCMAKE_BUILD_TYPE=Release` keyword, instead you need to specify during the build argument `cmake --build . --target package --config Release`. By default, the Debug configuration will be build.

**Comment by KerstinKeller** [comment]
Btw, thanks for the great project, I really enjoy using it 👍

**Comment by ArthurSonzogni** [comment]
Thanks!
I will try to fix this using your suggestion.

**Comment by ArthurSonzogni** [comment]
Thanks!
@KerstinKeller I released a new version:
https://github.com/ArthurSonzogni/git-tui/releases/tag/v1.0.9

If you find some time to try. Please let me know if this resolved your issue. Thanks you!

**Comment by ArthurSonzogni** [comment]
I see the binary went from ~350kB toward ~180kB. This is a good clue something happened.
