### ISSUE TITLE
Tabs Not Rendered

### ISSUE THREAD

**Issue by newOnahtaN** [ArthurSonzogni/git-tui#15]
Spaces seem to be rendered correctly in the diff view, but for some reason tabs are not:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/7771094/225419139-aff93a84-6f5e-4ac4-8974-37ff56e58581.png">

<img width="650" alt="image" src="https://user-images.githubusercontent.com/7771094/225419334-c0b8a30f-6ae9-4fbd-aa33-145321ee4ad6.png">

This is in the Windows terminal. Loving this software, by the way!

**Comment by ArthurSonzogni** [comment]
Thanks for your message and for the bug you reported.
I am not using tabs, and nobody noticed the bug before you apparently ;-)

Now, the big question: what's the of a tab? I hope you like 2.
If we really want, we can make it configurable at some point.

**Comment by newOnahtaN** [comment]
You rule! 

And I'll try to convince my team to stop using tabs ;)
