### ISSUE TITLE
Error: double free detected in tcache 2

### ISSUE THREAD

**Issue by szczad** [ArthurSonzogni/git-tui#4]
The program sometimes crashes with an error after hitting Ctl+C:
```
free(): double free detected in tcache 2
```

**Comment by ArthurSonzogni** [comment]
Does it still reproduce in v1.0.8?

If yes, could you please provide instructions about how to reproduce? OS? Tools?

**Comment by ArthurSonzogni** [comment]
I think it has been fixed in v1.0.9 and  I forget about it.
