### ISSUE TITLE
Column titles seem wrong?

### ISSUE THREAD

**Issue by Finii** [ArthurSonzogni/git-tui#7]
![image](https://user-images.githubusercontent.com/16012374/154292979-c0fc86aa-191b-43a5-9adf-ae5cfd8b0348.png)

Hmm, **Files** looks like commit titles and **Commit** looks like being the header line for files?

**Comment by ArthurSonzogni** [comment]
Indeed:
https://github.com/ArthurSonzogni/git-tui/blob/1259a261949f7c9ae7b1077f1c92e6426bba4e4a/src/log.cpp#L274-L289
Thanks! Do you want to make a PR?
